library verilog;
use verilog.vl_types.all;
entity Ejercicio_11 is
    port(
        SW0             : in     vl_logic;
        SW1             : in     vl_logic;
        SW2             : in     vl_logic;
        LED0            : out    vl_logic;
        LED1            : out    vl_logic;
        LED2            : out    vl_logic;
        LED3            : out    vl_logic;
        LED4            : out    vl_logic;
        LED5            : out    vl_logic;
        LED6            : out    vl_logic;
        LED7            : out    vl_logic;
        LED8            : out    vl_logic;
        LED9            : out    vl_logic;
        LED10           : out    vl_logic;
        LED11           : out    vl_logic;
        LED12           : out    vl_logic;
        LED13           : out    vl_logic;
        LED14           : out    vl_logic;
        LED15           : out    vl_logic;
        LED16           : out    vl_logic;
        LED17           : out    vl_logic;
        LED18           : out    vl_logic;
        LED19           : out    vl_logic;
        LED20           : out    vl_logic;
        LED21           : out    vl_logic;
        LED22           : out    vl_logic;
        LED23           : out    vl_logic;
        LED24           : out    vl_logic;
        LED25           : out    vl_logic;
        LED26           : out    vl_logic;
        LED27           : out    vl_logic;
        LED28           : out    vl_logic;
        LED29           : out    vl_logic;
        LED30           : out    vl_logic;
        LED31           : out    vl_logic;
        LED32           : out    vl_logic;
        LED33           : out    vl_logic;
        LED34           : out    vl_logic;
        LED35           : out    vl_logic;
        LED36           : out    vl_logic;
        LED37           : out    vl_logic;
        LED38           : out    vl_logic;
        LED39           : out    vl_logic;
        LED40           : out    vl_logic;
        LED41           : out    vl_logic
    );
end Ejercicio_11;
